language: ruby
dist: xenial
services:
  - xvfb
  - mysql
  - riak
  - rabbitmq
  - memcached
  - postgresql
  - mongodb
  - couchdb
  - redis-server
  - cassandra
  - neo4j
  - elasticsearch

script:
- ps aux
